/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRhRouteImport } from './routes/dashboard.rh'
import { Route as DashboardMedecinRouteImport } from './routes/dashboard.medecin'
import { Route as DashboardManagerRouteImport } from './routes/dashboard.manager'
import { Route as DashboardCollabRouteImport } from './routes/dashboard.collab'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DashboardRhIndexRouteImport } from './routes/dashboard.rh.index'
import { Route as DashboardMedecinIndexRouteImport } from './routes/dashboard.medecin.index'
import { Route as DashboardManagerIndexRouteImport } from './routes/dashboard.manager.index'
import { Route as DashboardCollabIndexRouteImport } from './routes/dashboard.collab.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardRhWorkflowsRouteImport } from './routes/dashboard.rh.workflows'
import { Route as DashboardRhProfileRouteImport } from './routes/dashboard.rh.profile'
import { Route as DashboardRhPeopleRouteImport } from './routes/dashboard.rh.people'
import { Route as DashboardRhMedicalRouteImport } from './routes/dashboard.rh.medical'
import { Route as DashboardRhKnowledgeRouteImport } from './routes/dashboard.rh.knowledge'
import { Route as DashboardRhDocumentsRouteImport } from './routes/dashboard.rh.documents'
import { Route as DashboardMedecinRequestsRouteImport } from './routes/dashboard.medecin.requests'
import { Route as DashboardMedecinRecordsRouteImport } from './routes/dashboard.medecin.records'
import { Route as DashboardMedecinProfileRouteImport } from './routes/dashboard.medecin.profile'
import { Route as DashboardMedecinAssistantRouteImport } from './routes/dashboard.medecin.assistant'
import { Route as DashboardManagerTeamRouteImport } from './routes/dashboard.manager.team'
import { Route as DashboardManagerSimulatorRouteImport } from './routes/dashboard.manager.simulator'
import { Route as DashboardManagerQvtRouteImport } from './routes/dashboard.manager.qvt'
import { Route as DashboardManagerProfileRouteImport } from './routes/dashboard.manager.profile'
import { Route as DashboardManagerLeaveRouteImport } from './routes/dashboard.manager.leave'
import { Route as DashboardManagerInsightsRouteImport } from './routes/dashboard.manager.insights'
import { Route as DashboardManagerAlertsRouteImport } from './routes/dashboard.manager.alerts'
import { Route as DashboardCollabProfileRouteImport } from './routes/dashboard.collab.profile'
import { Route as DashboardCollabPresenceRouteImport } from './routes/dashboard.collab.presence'
import { Route as DashboardCollabOnboardingRouteImport } from './routes/dashboard.collab.onboarding'
import { Route as DashboardCollabOffboardingRouteImport } from './routes/dashboard.collab.offboarding'
import { Route as DashboardCollabMedicalRouteImport } from './routes/dashboard.collab.medical'
import { Route as DashboardCollabLeaveRouteImport } from './routes/dashboard.collab.leave'
import { Route as DashboardCollabDocumentsRouteImport } from './routes/dashboard.collab.documents'
import { Route as DashboardCollabAssistantRouteImport } from './routes/dashboard.collab.assistant'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminSupervisionRouteImport } from './routes/dashboard.admin.supervision'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminSecurityRouteImport } from './routes/dashboard.admin.security'
import { Route as DashboardAdminProfileRouteImport } from './routes/dashboard.admin.profile'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api/public/seed-demo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRhRoute = DashboardRhRouteImport.update({
  id: '/dashboard/rh',
  path: '/dashboard/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMedecinRoute = DashboardMedecinRouteImport.update({
  id: '/dashboard/medecin',
  path: '/dashboard/medecin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManagerRoute = DashboardManagerRouteImport.update({
  id: '/dashboard/manager',
  path: '/dashboard/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCollabRoute = DashboardCollabRouteImport.update({
  id: '/dashboard/collab',
  path: '/dashboard/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRhIndexRoute = DashboardRhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRhRoute,
} as any)
const DashboardMedecinIndexRoute = DashboardMedecinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMedecinRoute,
} as any)
const DashboardManagerIndexRoute = DashboardManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardCollabIndexRoute = DashboardCollabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCollabRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardRhWorkflowsRoute = DashboardRhWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => DashboardRhRoute,
} as any)
const DashboardRhProfileRoute = DashboardRhProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRhRoute,
} as any)
const DashboardRhPeopleRoute = DashboardRhPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => DashboardRhRoute,
} as any)
const DashboardRhMedicalRoute = DashboardRhMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => DashboardRhRoute,
} as any)
const DashboardRhKnowledgeRoute = DashboardRhKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => DashboardRhRoute,
} as any)
const DashboardRhDocumentsRoute = DashboardRhDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRhRoute,
} as any)
const DashboardMedecinRequestsRoute =
  DashboardMedecinRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => DashboardMedecinRoute,
  } as any)
const DashboardMedecinRecordsRoute = DashboardMedecinRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DashboardMedecinRoute,
} as any)
const DashboardMedecinProfileRoute = DashboardMedecinProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardMedecinRoute,
} as any)
const DashboardMedecinAssistantRoute =
  DashboardMedecinAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => DashboardMedecinRoute,
  } as any)
const DashboardManagerTeamRoute = DashboardManagerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardManagerSimulatorRoute =
  DashboardManagerSimulatorRouteImport.update({
    id: '/simulator',
    path: '/simulator',
    getParentRoute: () => DashboardManagerRoute,
  } as any)
const DashboardManagerQvtRoute = DashboardManagerQvtRouteImport.update({
  id: '/qvt',
  path: '/qvt',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardManagerProfileRoute = DashboardManagerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardManagerLeaveRoute = DashboardManagerLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardManagerInsightsRoute =
  DashboardManagerInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => DashboardManagerRoute,
  } as any)
const DashboardManagerAlertsRoute = DashboardManagerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardManagerRoute,
} as any)
const DashboardCollabProfileRoute = DashboardCollabProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardCollabRoute,
} as any)
const DashboardCollabPresenceRoute = DashboardCollabPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => DashboardCollabRoute,
} as any)
const DashboardCollabOnboardingRoute =
  DashboardCollabOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => DashboardCollabRoute,
  } as any)
const DashboardCollabOffboardingRoute =
  DashboardCollabOffboardingRouteImport.update({
    id: '/offboarding',
    path: '/offboarding',
    getParentRoute: () => DashboardCollabRoute,
  } as any)
const DashboardCollabMedicalRoute = DashboardCollabMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => DashboardCollabRoute,
} as any)
const DashboardCollabLeaveRoute = DashboardCollabLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => DashboardCollabRoute,
} as any)
const DashboardCollabDocumentsRoute =
  DashboardCollabDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardCollabRoute,
  } as any)
const DashboardCollabAssistantRoute =
  DashboardCollabAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => DashboardCollabRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSupervisionRoute =
  DashboardAdminSupervisionRouteImport.update({
    id: '/supervision',
    path: '/supervision',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSecurityRoute = DashboardAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminProfileRoute = DashboardAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/collab': typeof DashboardCollabRouteWithChildren
  '/dashboard/manager': typeof DashboardManagerRouteWithChildren
  '/dashboard/medecin': typeof DashboardMedecinRouteWithChildren
  '/dashboard/rh': typeof DashboardRhRouteWithChildren
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/dashboard/admin/profile': typeof DashboardAdminProfileRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/supervision': typeof DashboardAdminSupervisionRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/collab/assistant': typeof DashboardCollabAssistantRoute
  '/dashboard/collab/documents': typeof DashboardCollabDocumentsRoute
  '/dashboard/collab/leave': typeof DashboardCollabLeaveRoute
  '/dashboard/collab/medical': typeof DashboardCollabMedicalRoute
  '/dashboard/collab/offboarding': typeof DashboardCollabOffboardingRoute
  '/dashboard/collab/onboarding': typeof DashboardCollabOnboardingRoute
  '/dashboard/collab/presence': typeof DashboardCollabPresenceRoute
  '/dashboard/collab/profile': typeof DashboardCollabProfileRoute
  '/dashboard/manager/alerts': typeof DashboardManagerAlertsRoute
  '/dashboard/manager/insights': typeof DashboardManagerInsightsRoute
  '/dashboard/manager/leave': typeof DashboardManagerLeaveRoute
  '/dashboard/manager/profile': typeof DashboardManagerProfileRoute
  '/dashboard/manager/qvt': typeof DashboardManagerQvtRoute
  '/dashboard/manager/simulator': typeof DashboardManagerSimulatorRoute
  '/dashboard/manager/team': typeof DashboardManagerTeamRoute
  '/dashboard/medecin/assistant': typeof DashboardMedecinAssistantRoute
  '/dashboard/medecin/profile': typeof DashboardMedecinProfileRoute
  '/dashboard/medecin/records': typeof DashboardMedecinRecordsRoute
  '/dashboard/medecin/requests': typeof DashboardMedecinRequestsRoute
  '/dashboard/rh/documents': typeof DashboardRhDocumentsRoute
  '/dashboard/rh/knowledge': typeof DashboardRhKnowledgeRoute
  '/dashboard/rh/medical': typeof DashboardRhMedicalRoute
  '/dashboard/rh/people': typeof DashboardRhPeopleRoute
  '/dashboard/rh/profile': typeof DashboardRhProfileRoute
  '/dashboard/rh/workflows': typeof DashboardRhWorkflowsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/collab/': typeof DashboardCollabIndexRoute
  '/dashboard/manager/': typeof DashboardManagerIndexRoute
  '/dashboard/medecin/': typeof DashboardMedecinIndexRoute
  '/dashboard/rh/': typeof DashboardRhIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/dashboard/admin/profile': typeof DashboardAdminProfileRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/supervision': typeof DashboardAdminSupervisionRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/collab/assistant': typeof DashboardCollabAssistantRoute
  '/dashboard/collab/documents': typeof DashboardCollabDocumentsRoute
  '/dashboard/collab/leave': typeof DashboardCollabLeaveRoute
  '/dashboard/collab/medical': typeof DashboardCollabMedicalRoute
  '/dashboard/collab/offboarding': typeof DashboardCollabOffboardingRoute
  '/dashboard/collab/onboarding': typeof DashboardCollabOnboardingRoute
  '/dashboard/collab/presence': typeof DashboardCollabPresenceRoute
  '/dashboard/collab/profile': typeof DashboardCollabProfileRoute
  '/dashboard/manager/alerts': typeof DashboardManagerAlertsRoute
  '/dashboard/manager/insights': typeof DashboardManagerInsightsRoute
  '/dashboard/manager/leave': typeof DashboardManagerLeaveRoute
  '/dashboard/manager/profile': typeof DashboardManagerProfileRoute
  '/dashboard/manager/qvt': typeof DashboardManagerQvtRoute
  '/dashboard/manager/simulator': typeof DashboardManagerSimulatorRoute
  '/dashboard/manager/team': typeof DashboardManagerTeamRoute
  '/dashboard/medecin/assistant': typeof DashboardMedecinAssistantRoute
  '/dashboard/medecin/profile': typeof DashboardMedecinProfileRoute
  '/dashboard/medecin/records': typeof DashboardMedecinRecordsRoute
  '/dashboard/medecin/requests': typeof DashboardMedecinRequestsRoute
  '/dashboard/rh/documents': typeof DashboardRhDocumentsRoute
  '/dashboard/rh/knowledge': typeof DashboardRhKnowledgeRoute
  '/dashboard/rh/medical': typeof DashboardRhMedicalRoute
  '/dashboard/rh/people': typeof DashboardRhPeopleRoute
  '/dashboard/rh/profile': typeof DashboardRhProfileRoute
  '/dashboard/rh/workflows': typeof DashboardRhWorkflowsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/collab': typeof DashboardCollabIndexRoute
  '/dashboard/manager': typeof DashboardManagerIndexRoute
  '/dashboard/medecin': typeof DashboardMedecinIndexRoute
  '/dashboard/rh': typeof DashboardRhIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/collab': typeof DashboardCollabRouteWithChildren
  '/dashboard/manager': typeof DashboardManagerRouteWithChildren
  '/dashboard/medecin': typeof DashboardMedecinRouteWithChildren
  '/dashboard/rh': typeof DashboardRhRouteWithChildren
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/dashboard/admin/profile': typeof DashboardAdminProfileRoute
  '/dashboard/admin/security': typeof DashboardAdminSecurityRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/supervision': typeof DashboardAdminSupervisionRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/collab/assistant': typeof DashboardCollabAssistantRoute
  '/dashboard/collab/documents': typeof DashboardCollabDocumentsRoute
  '/dashboard/collab/leave': typeof DashboardCollabLeaveRoute
  '/dashboard/collab/medical': typeof DashboardCollabMedicalRoute
  '/dashboard/collab/offboarding': typeof DashboardCollabOffboardingRoute
  '/dashboard/collab/onboarding': typeof DashboardCollabOnboardingRoute
  '/dashboard/collab/presence': typeof DashboardCollabPresenceRoute
  '/dashboard/collab/profile': typeof DashboardCollabProfileRoute
  '/dashboard/manager/alerts': typeof DashboardManagerAlertsRoute
  '/dashboard/manager/insights': typeof DashboardManagerInsightsRoute
  '/dashboard/manager/leave': typeof DashboardManagerLeaveRoute
  '/dashboard/manager/profile': typeof DashboardManagerProfileRoute
  '/dashboard/manager/qvt': typeof DashboardManagerQvtRoute
  '/dashboard/manager/simulator': typeof DashboardManagerSimulatorRoute
  '/dashboard/manager/team': typeof DashboardManagerTeamRoute
  '/dashboard/medecin/assistant': typeof DashboardMedecinAssistantRoute
  '/dashboard/medecin/profile': typeof DashboardMedecinProfileRoute
  '/dashboard/medecin/records': typeof DashboardMedecinRecordsRoute
  '/dashboard/medecin/requests': typeof DashboardMedecinRequestsRoute
  '/dashboard/rh/documents': typeof DashboardRhDocumentsRoute
  '/dashboard/rh/knowledge': typeof DashboardRhKnowledgeRoute
  '/dashboard/rh/medical': typeof DashboardRhMedicalRoute
  '/dashboard/rh/people': typeof DashboardRhPeopleRoute
  '/dashboard/rh/profile': typeof DashboardRhProfileRoute
  '/dashboard/rh/workflows': typeof DashboardRhWorkflowsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/collab/': typeof DashboardCollabIndexRoute
  '/dashboard/manager/': typeof DashboardManagerIndexRoute
  '/dashboard/medecin/': typeof DashboardMedecinIndexRoute
  '/dashboard/rh/': typeof DashboardRhIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/dashboard/admin'
    | '/dashboard/collab'
    | '/dashboard/manager'
    | '/dashboard/medecin'
    | '/dashboard/rh'
    | '/api/public/seed-demo'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/security'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/supervision'
    | '/dashboard/admin/users'
    | '/dashboard/collab/assistant'
    | '/dashboard/collab/documents'
    | '/dashboard/collab/leave'
    | '/dashboard/collab/medical'
    | '/dashboard/collab/offboarding'
    | '/dashboard/collab/onboarding'
    | '/dashboard/collab/presence'
    | '/dashboard/collab/profile'
    | '/dashboard/manager/alerts'
    | '/dashboard/manager/insights'
    | '/dashboard/manager/leave'
    | '/dashboard/manager/profile'
    | '/dashboard/manager/qvt'
    | '/dashboard/manager/simulator'
    | '/dashboard/manager/team'
    | '/dashboard/medecin/assistant'
    | '/dashboard/medecin/profile'
    | '/dashboard/medecin/records'
    | '/dashboard/medecin/requests'
    | '/dashboard/rh/documents'
    | '/dashboard/rh/knowledge'
    | '/dashboard/rh/medical'
    | '/dashboard/rh/people'
    | '/dashboard/rh/profile'
    | '/dashboard/rh/workflows'
    | '/dashboard/admin/'
    | '/dashboard/collab/'
    | '/dashboard/manager/'
    | '/dashboard/medecin/'
    | '/dashboard/rh/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/api/public/seed-demo'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/security'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/supervision'
    | '/dashboard/admin/users'
    | '/dashboard/collab/assistant'
    | '/dashboard/collab/documents'
    | '/dashboard/collab/leave'
    | '/dashboard/collab/medical'
    | '/dashboard/collab/offboarding'
    | '/dashboard/collab/onboarding'
    | '/dashboard/collab/presence'
    | '/dashboard/collab/profile'
    | '/dashboard/manager/alerts'
    | '/dashboard/manager/insights'
    | '/dashboard/manager/leave'
    | '/dashboard/manager/profile'
    | '/dashboard/manager/qvt'
    | '/dashboard/manager/simulator'
    | '/dashboard/manager/team'
    | '/dashboard/medecin/assistant'
    | '/dashboard/medecin/profile'
    | '/dashboard/medecin/records'
    | '/dashboard/medecin/requests'
    | '/dashboard/rh/documents'
    | '/dashboard/rh/knowledge'
    | '/dashboard/rh/medical'
    | '/dashboard/rh/people'
    | '/dashboard/rh/profile'
    | '/dashboard/rh/workflows'
    | '/dashboard/admin'
    | '/dashboard/collab'
    | '/dashboard/manager'
    | '/dashboard/medecin'
    | '/dashboard/rh'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/chat'
    | '/dashboard/admin'
    | '/dashboard/collab'
    | '/dashboard/manager'
    | '/dashboard/medecin'
    | '/dashboard/rh'
    | '/api/public/seed-demo'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/security'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/supervision'
    | '/dashboard/admin/users'
    | '/dashboard/collab/assistant'
    | '/dashboard/collab/documents'
    | '/dashboard/collab/leave'
    | '/dashboard/collab/medical'
    | '/dashboard/collab/offboarding'
    | '/dashboard/collab/onboarding'
    | '/dashboard/collab/presence'
    | '/dashboard/collab/profile'
    | '/dashboard/manager/alerts'
    | '/dashboard/manager/insights'
    | '/dashboard/manager/leave'
    | '/dashboard/manager/profile'
    | '/dashboard/manager/qvt'
    | '/dashboard/manager/simulator'
    | '/dashboard/manager/team'
    | '/dashboard/medecin/assistant'
    | '/dashboard/medecin/profile'
    | '/dashboard/medecin/records'
    | '/dashboard/medecin/requests'
    | '/dashboard/rh/documents'
    | '/dashboard/rh/knowledge'
    | '/dashboard/rh/medical'
    | '/dashboard/rh/people'
    | '/dashboard/rh/profile'
    | '/dashboard/rh/workflows'
    | '/dashboard/admin/'
    | '/dashboard/collab/'
    | '/dashboard/manager/'
    | '/dashboard/medecin/'
    | '/dashboard/rh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardCollabRoute: typeof DashboardCollabRouteWithChildren
  DashboardManagerRoute: typeof DashboardManagerRouteWithChildren
  DashboardMedecinRoute: typeof DashboardMedecinRouteWithChildren
  DashboardRhRoute: typeof DashboardRhRouteWithChildren
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/rh': {
      id: '/dashboard/rh'
      path: '/dashboard/rh'
      fullPath: '/dashboard/rh'
      preLoaderRoute: typeof DashboardRhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/medecin': {
      id: '/dashboard/medecin'
      path: '/dashboard/medecin'
      fullPath: '/dashboard/medecin'
      preLoaderRoute: typeof DashboardMedecinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manager': {
      id: '/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof DashboardManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/collab': {
      id: '/dashboard/collab'
      path: '/dashboard/collab'
      fullPath: '/dashboard/collab'
      preLoaderRoute: typeof DashboardCollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/rh/': {
      id: '/dashboard/rh/'
      path: '/'
      fullPath: '/dashboard/rh/'
      preLoaderRoute: typeof DashboardRhIndexRouteImport
      parentRoute: typeof DashboardRhRoute
    }
    '/dashboard/medecin/': {
      id: '/dashboard/medecin/'
      path: '/'
      fullPath: '/dashboard/medecin/'
      preLoaderRoute: typeof DashboardMedecinIndexRouteImport
      parentRoute: typeof DashboardMedecinRoute
    }
    '/dashboard/manager/': {
      id: '/dashboard/manager/'
      path: '/'
      fullPath: '/dashboard/manager/'
      preLoaderRoute: typeof DashboardManagerIndexRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/collab/': {
      id: '/dashboard/collab/'
      path: '/'
      fullPath: '/dashboard/collab/'
      preLoaderRoute: typeof DashboardCollabIndexRouteImport
      parentRoute: typeof DashboardCollabRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/rh/workflows': {
      id: '/dashboard/rh/workflows'
      path: '/workflows'
      fullPath: '/dashboard/rh/workflows'
      preLoaderRoute: typeof DashboardRhWorkflowsRouteImport
      parentRoute: typeof DashboardRhRoute
    }
    '/dashboard/rh/profile': {
      id: '/dashboard/rh/profile'
      path: '/profile'
      fullPath: '/dashboard/rh/profile'
      preLoaderRoute: typeof DashboardRhProfileRouteImport
      parentRoute: typeof DashboardRhRoute
    }
    '/dashboard/rh/people': {
      id: '/dashboard/rh/people'
      path: '/people'
      fullPath: '/dashboard/rh/people'
      preLoaderRoute: typeof DashboardRhPeopleRouteImport
      parentRoute: typeof DashboardRhRoute
    }
    '/dashboard/rh/medical': {
      id: '/dashboard/rh/medical'
      path: '/medical'
      fullPath: '/dashboard/rh/medical'
      preLoaderRoute: typeof DashboardRhMedicalRouteImport
      parentRoute: typeof DashboardRhRoute
    }
    '/dashboard/rh/knowledge': {
      id: '/dashboard/rh/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/rh/knowledge'
      preLoaderRoute: typeof DashboardRhKnowledgeRouteImport
      parentRoute: typeof DashboardRhRoute
    }
    '/dashboard/rh/documents': {
      id: '/dashboard/rh/documents'
      path: '/documents'
      fullPath: '/dashboard/rh/documents'
      preLoaderRoute: typeof DashboardRhDocumentsRouteImport
      parentRoute: typeof DashboardRhRoute
    }
    '/dashboard/medecin/requests': {
      id: '/dashboard/medecin/requests'
      path: '/requests'
      fullPath: '/dashboard/medecin/requests'
      preLoaderRoute: typeof DashboardMedecinRequestsRouteImport
      parentRoute: typeof DashboardMedecinRoute
    }
    '/dashboard/medecin/records': {
      id: '/dashboard/medecin/records'
      path: '/records'
      fullPath: '/dashboard/medecin/records'
      preLoaderRoute: typeof DashboardMedecinRecordsRouteImport
      parentRoute: typeof DashboardMedecinRoute
    }
    '/dashboard/medecin/profile': {
      id: '/dashboard/medecin/profile'
      path: '/profile'
      fullPath: '/dashboard/medecin/profile'
      preLoaderRoute: typeof DashboardMedecinProfileRouteImport
      parentRoute: typeof DashboardMedecinRoute
    }
    '/dashboard/medecin/assistant': {
      id: '/dashboard/medecin/assistant'
      path: '/assistant'
      fullPath: '/dashboard/medecin/assistant'
      preLoaderRoute: typeof DashboardMedecinAssistantRouteImport
      parentRoute: typeof DashboardMedecinRoute
    }
    '/dashboard/manager/team': {
      id: '/dashboard/manager/team'
      path: '/team'
      fullPath: '/dashboard/manager/team'
      preLoaderRoute: typeof DashboardManagerTeamRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/manager/simulator': {
      id: '/dashboard/manager/simulator'
      path: '/simulator'
      fullPath: '/dashboard/manager/simulator'
      preLoaderRoute: typeof DashboardManagerSimulatorRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/manager/qvt': {
      id: '/dashboard/manager/qvt'
      path: '/qvt'
      fullPath: '/dashboard/manager/qvt'
      preLoaderRoute: typeof DashboardManagerQvtRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/manager/profile': {
      id: '/dashboard/manager/profile'
      path: '/profile'
      fullPath: '/dashboard/manager/profile'
      preLoaderRoute: typeof DashboardManagerProfileRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/manager/leave': {
      id: '/dashboard/manager/leave'
      path: '/leave'
      fullPath: '/dashboard/manager/leave'
      preLoaderRoute: typeof DashboardManagerLeaveRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/manager/insights': {
      id: '/dashboard/manager/insights'
      path: '/insights'
      fullPath: '/dashboard/manager/insights'
      preLoaderRoute: typeof DashboardManagerInsightsRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/manager/alerts': {
      id: '/dashboard/manager/alerts'
      path: '/alerts'
      fullPath: '/dashboard/manager/alerts'
      preLoaderRoute: typeof DashboardManagerAlertsRouteImport
      parentRoute: typeof DashboardManagerRoute
    }
    '/dashboard/collab/profile': {
      id: '/dashboard/collab/profile'
      path: '/profile'
      fullPath: '/dashboard/collab/profile'
      preLoaderRoute: typeof DashboardCollabProfileRouteImport
      parentRoute: typeof DashboardCollabRoute
    }
    '/dashboard/collab/presence': {
      id: '/dashboard/collab/presence'
      path: '/presence'
      fullPath: '/dashboard/collab/presence'
      preLoaderRoute: typeof DashboardCollabPresenceRouteImport
      parentRoute: typeof DashboardCollabRoute
    }
    '/dashboard/collab/onboarding': {
      id: '/dashboard/collab/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/collab/onboarding'
      preLoaderRoute: typeof DashboardCollabOnboardingRouteImport
      parentRoute: typeof DashboardCollabRoute
    }
    '/dashboard/collab/offboarding': {
      id: '/dashboard/collab/offboarding'
      path: '/offboarding'
      fullPath: '/dashboard/collab/offboarding'
      preLoaderRoute: typeof DashboardCollabOffboardingRouteImport
      parentRoute: typeof DashboardCollabRoute
    }
    '/dashboard/collab/medical': {
      id: '/dashboard/collab/medical'
      path: '/medical'
      fullPath: '/dashboard/collab/medical'
      preLoaderRoute: typeof DashboardCollabMedicalRouteImport
      parentRoute: typeof DashboardCollabRoute
    }
    '/dashboard/collab/leave': {
      id: '/dashboard/collab/leave'
      path: '/leave'
      fullPath: '/dashboard/collab/leave'
      preLoaderRoute: typeof DashboardCollabLeaveRouteImport
      parentRoute: typeof DashboardCollabRoute
    }
    '/dashboard/collab/documents': {
      id: '/dashboard/collab/documents'
      path: '/documents'
      fullPath: '/dashboard/collab/documents'
      preLoaderRoute: typeof DashboardCollabDocumentsRouteImport
      parentRoute: typeof DashboardCollabRoute
    }
    '/dashboard/collab/assistant': {
      id: '/dashboard/collab/assistant'
      path: '/assistant'
      fullPath: '/dashboard/collab/assistant'
      preLoaderRoute: typeof DashboardCollabAssistantRouteImport
      parentRoute: typeof DashboardCollabRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/supervision': {
      id: '/dashboard/admin/supervision'
      path: '/supervision'
      fullPath: '/dashboard/admin/supervision'
      preLoaderRoute: typeof DashboardAdminSupervisionRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/security': {
      id: '/dashboard/admin/security'
      path: '/security'
      fullPath: '/dashboard/admin/security'
      preLoaderRoute: typeof DashboardAdminSecurityRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/profile': {
      id: '/dashboard/admin/profile'
      path: '/profile'
      fullPath: '/dashboard/admin/profile'
      preLoaderRoute: typeof DashboardAdminProfileRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminProfileRoute: typeof DashboardAdminProfileRoute
  DashboardAdminSecurityRoute: typeof DashboardAdminSecurityRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminSupervisionRoute: typeof DashboardAdminSupervisionRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminProfileRoute: DashboardAdminProfileRoute,
  DashboardAdminSecurityRoute: DashboardAdminSecurityRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminSupervisionRoute: DashboardAdminSupervisionRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardCollabRouteChildren {
  DashboardCollabAssistantRoute: typeof DashboardCollabAssistantRoute
  DashboardCollabDocumentsRoute: typeof DashboardCollabDocumentsRoute
  DashboardCollabLeaveRoute: typeof DashboardCollabLeaveRoute
  DashboardCollabMedicalRoute: typeof DashboardCollabMedicalRoute
  DashboardCollabOffboardingRoute: typeof DashboardCollabOffboardingRoute
  DashboardCollabOnboardingRoute: typeof DashboardCollabOnboardingRoute
  DashboardCollabPresenceRoute: typeof DashboardCollabPresenceRoute
  DashboardCollabProfileRoute: typeof DashboardCollabProfileRoute
  DashboardCollabIndexRoute: typeof DashboardCollabIndexRoute
}

const DashboardCollabRouteChildren: DashboardCollabRouteChildren = {
  DashboardCollabAssistantRoute: DashboardCollabAssistantRoute,
  DashboardCollabDocumentsRoute: DashboardCollabDocumentsRoute,
  DashboardCollabLeaveRoute: DashboardCollabLeaveRoute,
  DashboardCollabMedicalRoute: DashboardCollabMedicalRoute,
  DashboardCollabOffboardingRoute: DashboardCollabOffboardingRoute,
  DashboardCollabOnboardingRoute: DashboardCollabOnboardingRoute,
  DashboardCollabPresenceRoute: DashboardCollabPresenceRoute,
  DashboardCollabProfileRoute: DashboardCollabProfileRoute,
  DashboardCollabIndexRoute: DashboardCollabIndexRoute,
}

const DashboardCollabRouteWithChildren = DashboardCollabRoute._addFileChildren(
  DashboardCollabRouteChildren,
)

interface DashboardManagerRouteChildren {
  DashboardManagerAlertsRoute: typeof DashboardManagerAlertsRoute
  DashboardManagerInsightsRoute: typeof DashboardManagerInsightsRoute
  DashboardManagerLeaveRoute: typeof DashboardManagerLeaveRoute
  DashboardManagerProfileRoute: typeof DashboardManagerProfileRoute
  DashboardManagerQvtRoute: typeof DashboardManagerQvtRoute
  DashboardManagerSimulatorRoute: typeof DashboardManagerSimulatorRoute
  DashboardManagerTeamRoute: typeof DashboardManagerTeamRoute
  DashboardManagerIndexRoute: typeof DashboardManagerIndexRoute
}

const DashboardManagerRouteChildren: DashboardManagerRouteChildren = {
  DashboardManagerAlertsRoute: DashboardManagerAlertsRoute,
  DashboardManagerInsightsRoute: DashboardManagerInsightsRoute,
  DashboardManagerLeaveRoute: DashboardManagerLeaveRoute,
  DashboardManagerProfileRoute: DashboardManagerProfileRoute,
  DashboardManagerQvtRoute: DashboardManagerQvtRoute,
  DashboardManagerSimulatorRoute: DashboardManagerSimulatorRoute,
  DashboardManagerTeamRoute: DashboardManagerTeamRoute,
  DashboardManagerIndexRoute: DashboardManagerIndexRoute,
}

const DashboardManagerRouteWithChildren =
  DashboardManagerRoute._addFileChildren(DashboardManagerRouteChildren)

interface DashboardMedecinRouteChildren {
  DashboardMedecinAssistantRoute: typeof DashboardMedecinAssistantRoute
  DashboardMedecinProfileRoute: typeof DashboardMedecinProfileRoute
  DashboardMedecinRecordsRoute: typeof DashboardMedecinRecordsRoute
  DashboardMedecinRequestsRoute: typeof DashboardMedecinRequestsRoute
  DashboardMedecinIndexRoute: typeof DashboardMedecinIndexRoute
}

const DashboardMedecinRouteChildren: DashboardMedecinRouteChildren = {
  DashboardMedecinAssistantRoute: DashboardMedecinAssistantRoute,
  DashboardMedecinProfileRoute: DashboardMedecinProfileRoute,
  DashboardMedecinRecordsRoute: DashboardMedecinRecordsRoute,
  DashboardMedecinRequestsRoute: DashboardMedecinRequestsRoute,
  DashboardMedecinIndexRoute: DashboardMedecinIndexRoute,
}

const DashboardMedecinRouteWithChildren =
  DashboardMedecinRoute._addFileChildren(DashboardMedecinRouteChildren)

interface DashboardRhRouteChildren {
  DashboardRhDocumentsRoute: typeof DashboardRhDocumentsRoute
  DashboardRhKnowledgeRoute: typeof DashboardRhKnowledgeRoute
  DashboardRhMedicalRoute: typeof DashboardRhMedicalRoute
  DashboardRhPeopleRoute: typeof DashboardRhPeopleRoute
  DashboardRhProfileRoute: typeof DashboardRhProfileRoute
  DashboardRhWorkflowsRoute: typeof DashboardRhWorkflowsRoute
  DashboardRhIndexRoute: typeof DashboardRhIndexRoute
}

const DashboardRhRouteChildren: DashboardRhRouteChildren = {
  DashboardRhDocumentsRoute: DashboardRhDocumentsRoute,
  DashboardRhKnowledgeRoute: DashboardRhKnowledgeRoute,
  DashboardRhMedicalRoute: DashboardRhMedicalRoute,
  DashboardRhPeopleRoute: DashboardRhPeopleRoute,
  DashboardRhProfileRoute: DashboardRhProfileRoute,
  DashboardRhWorkflowsRoute: DashboardRhWorkflowsRoute,
  DashboardRhIndexRoute: DashboardRhIndexRoute,
}

const DashboardRhRouteWithChildren = DashboardRhRoute._addFileChildren(
  DashboardRhRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardCollabRoute: DashboardCollabRouteWithChildren,
  DashboardManagerRoute: DashboardManagerRouteWithChildren,
  DashboardMedecinRoute: DashboardMedecinRouteWithChildren,
  DashboardRhRoute: DashboardRhRouteWithChildren,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
